insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
insert into suggestion(content, create_date, status, is_sent, likes) values("Can you raise my salary?", curdate(), 1, 1, 0);
commit;